routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/edificios', 'BuildingController');

Route::resource('/estructura', 'BuildingItemsController');

Route::resource('/espacios', 'SpaceController');

Route::resource('/egresos', 'ExpenseController');

Route::resource('/asociaciones', 'ResidentUnityController');

Route::resource('/fondos', 'FundController');

Route::resource('/items_individuales', 'IndividualItemsController');

Route::resource('/gastos_individuales', 'IndividualExpensesController');

Route::resource('/servicios_individuales', 'IndividualItemsController');

Route::resource('/proveedores', 'ProvidersController');

Route::resource('/unidades', 'UnityController');

Route::resource('/usuario', 'UserController');

Route::get('/usuarioMyExpenses', 'UserController@myExpense');

Route::get('/usuarioBuildingExpenses', 'UserController@buildingExpense');

Route::get('/usuarioRent', 'UserController@rent');

Route::resource('/extension_unidad', 'UnityExtensionController');

Route::get('/dashboard/{id}', 'HomeController@dashboard');

Route::post('/unidades/import', 'UnityController@import');

Route::get('/personal', 'UserController@personal');

Route::get('/inquilino', 'UserController@inquilino');

Route::get('/getIndividualByUnity/{unity_id}', 'HelperController@getIndividualByUnity');

Route::get('/getInquilino/{unity_id}', 'HelperController@getInquilino');

Route::post('/createIndividual', 'HelperController@createIndividual');

Route::get('/gastos_unidad', 'UnityController@expenses');

Route::get('/userLogout', 'HomeController@userLogout');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
		'rut', 'phone', 'type',
		'building_id', 'unity_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

	const TYPES = [
		0=>'Super Admin',
		1=>'Admin',
		2=>'Usuario',
		3=>'Propietario',
		4=>'Residente',
		5=>'Personal',
		6=>'Comite'
	];
	//comite puede ver lo que pasa en el edificio solo para ver
	//

	public function personalDetail()
	{
		return $this->hasOne('App\PersonalDetails');
	}

	public function residentunity()
	{
		return $this->hasMany('App\ResidentUnity');
	}

	public function getTypeLabelAttribute()
	{
		return Self::TYPES[$this->type];
    }
    
    public function getAlicuotaAttribute() {
        $pro = 0;
        foreach ($this->residentunity as $key => $d) {
            $pro = (float)$d->unity->prorateo + (float)$pro;
        }
        return $pro;
    }

}

resources/views/clients/buildingExpense.blade.php
@extends('layouts.app')

@section('css')
	<link href="/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection

@section('content')

<div class="form-group row">
	<div class="col-md-8">
		<h1>Gastos de la Comunidad</h1>
	</div>
</div>

<div class="card shadow mb-4">

	<div class="card-body">
	  <div class="table-responsive">
		<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
			<div class="form-group row">
				<div class="col-md-8">
					<h3>Gastos Generales</h3>
				</div>
			</div>
		  <thead>
			<tr>
			  <th>Items</th>
			  <th>Descripcion</th>
			  <th>Monto</th>
			  <th>Alicuota %</th>
			  <th>A pagar</th>
			</tr>
		  </thead>

		  <tbody>
			@foreach ($remus as $key => $u)
			<tr>
				<td>{{$u->item_id}}</td>
				<td>Remuneraciones y Honorarios</td>
				<td>{{$u->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u->amount}}</td>
				</tr>
			@endforeach
			@foreach ($mantens as $key1 => $u1)
			<tr>
				<td>{{$u1->item_id}}</td>
				<td>Mantenciones</td>
				<td>{{$u1->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u1->amount}}</td>
				</tr>
			@endforeach
			@foreach ($repairs as $key2 => $u2)
			<tr>
				<td>{{$u2->item_id}}</td>
				<td>Reparaciones</td>
				<td>{{$u2->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u2->amount}}</td>
				</tr>
			@endforeach
			@foreach ($basicCs as $key3 => $u3)
			<tr>
				<td>{{$u3->item_id}}</td>
				<td>Consumos Básicos</td>
				<td>{{$u3->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u3->amount}}</td>
				</tr>
			@endforeach
			@foreach ($insumos as $key4 => $u4)
			<tr>
				<td>{{$u4->item_id}}</td>
				<td>Insumos</td>
				<td>{{$u4->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u4->amount}}</td>
				</tr>
			@endforeach
			@foreach ($otherCs as $key5 => $u5)
			<tr>
				<td>{{$u5->item_id}}</td>
				<td>Otros Gastos</td>
				<td>{{$u->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u5->amount}}</td>
				</tr>
			@endforeach
			@foreach ($otherIs as $key6 => $u6)
			<tr>
				<td>{{$u6->item_id}}</td>
				<td>Otros Ingresos</td>
				<td>{{$u6->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u6->amount}}</td>
				</tr>
			@endforeach
			<tr>
				<td>Total</td>
				<td></td>
				<td></td>
				<td></td>
			   <td>Pagar</td>
				</tr>

		  </tbody>
		</table>
	  </div>
	</div>
  </div>
@endsection

@section('scripts')

	<!-- Page level plugins -->
	<script src="vendor/datatables/jquery.dataTables.min.js"></script>
	<script src="vendor/datatables/dataTables.bootstrap4.min.js"></script>

	<!-- Page level custom scripts -->
	<script src="js/demo/datatables-demo.js"></script>
	<script src="js/serializeObject.js"></script>
	<script type="text/javascript">
		$(function () {

		})
	</script>
@endsection

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('css')
	<link href="/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection

@section('content')

<div class="card shadow mb-4">

	<div class="card-body">
	  <div class="table-responsive">
		<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
			<div class="form-group row">
				<div class="col-md-4">
					<select class="form-control" name="type">
					  <option value="">Seleccione Fecha de Facturacion</option>
					  <option value="1">01/2020</option>
					  <option value="2">02/2020</option>
					</select>
				</div>
		  </div>
		  <thead>
			<tr>
			  <th>Items</th>
			  <th>Costo</th>
			  <th>Tipo</th>
			</tr>
		  </thead>

		  <tbody>
				  <tr>
					<td></td>
					<td></td>
					<td></td>
				</tr>


		  </tbody>
		</table>
	  </div>
	</div>
  </div>
@endsection

@section('scripts')

	<!-- Page level plugins -->
	<script src="vendor/datatables/jquery.dataTables.min.js"></script>
	<script src="vendor/datatables/dataTables.bootstrap4.min.js"></script>

	<!-- Page level custom scripts -->
	<script src="js/demo/datatables-demo.js"></script>
	<script src="js/serializeObject.js"></script>
	<script type="text/javascript">
		$(function () {

		})
	</script>
@endsection

resources/views/clients/myExpense.blade.php
@extends('layouts.app')

@section('css')
	<link href="/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection

@section('content')


<div class="form-group row">
	<div class="col-md-8">
		<h1>Mis Gastos Comunes</h1>
	</div>
</div>

<div class="card shadow mb-4">

	<div class="card-body">
	  <div class="table-responsive">
		<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
			<div class="form-group row">
				<div class="col-md-8">
					<h3>Mis Gastos Comunes</h3>
				</div>
			</div>
		  <thead>
			<tr>
			  <th>Items</th>
			  <th>Descripcion</th>
			  <th>Monto</th>
			  <th>Alicuota %</th>
			  <th>A pagar</th>
			</tr>
		  </thead>

		  <tbody>
			
			<tr>
				<td>1</td>
				<td>Remuneraciones y Honorarios</td>
				<td> 
					@php
						$mount = 0;
						foreach ($remus as $key => $r) {
							$mount =  $mount + $r->amount;
						}
						echo $mount;
					@endphp
				</td>
				<td>{{$user->alicuota}}</td>
			   	<td>{{ $mount / $user->alicuota }} </td>
			</tr>
			
			
			@foreach ($mantens as $key1 => $u1)
			<tr>
				<td>{{$u1->item_id}}</td>
				<td>Mantenciones</td>
				<td>{{$u1->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u1->amount}}</td>
				</tr>
			@endforeach
			@foreach ($repairs as $key2 => $u2)
			<tr>
				<td>{{$u2->item_id}}</td>
				<td>Reparaciones</td>
				<td>{{$u2->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u2->amount}}</td>
				</tr>
			@endforeach
			@foreach ($basicCs as $key3 => $u3)
			<tr>
				<td>{{$u3->item_id}}</td>
				<td>Consumos Básicos</td>
				<td>{{$u3->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u3->amount}}</td>
				</tr>
			@endforeach
			@foreach ($insumos as $key4 => $u4)
			<tr>
				<td>{{$u4->item_id}}</td>
				<td>Insumos</td>
				<td>{{$u4->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u4->amount}}</td>
				</tr>
			@endforeach
			@foreach ($otherCs as $key5 => $u5)
			<tr>
				<td>{{$u5->item_id}}</td>
				<td>Otros Gastos</td>
				<td>{{$u->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u5->amount}}</td>
				</tr>
			@endforeach
			@foreach ($otherIs as $key6 => $u6)
			<tr>
				<td>{{$u6->item_id}}</td>
				<td>Otros Ingresos</td>
				<td>{{$u6->amount}}</td>
				<td>0.7661 %</td>
			   <td>{{$u6->amount}}</td>
				</tr>
			@endforeach
			<tr>
				<td>Total</td>
				<td></td>
				<td></td>
				<td></td>
			   <td>Pagar</td>
				</tr>

		  </tbody>
		</table>
	  </div>
	</div>
  </div>

  <div class="card shadow mb-4">

	<div class="card-body">
	  <div class="table-responsive">
		<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
			<div class="form-group row">
				<div class="col-md-8">
					<h3>Mis Gastos Individuales</h3>
				</div>
		  </div>
		  <thead>
			<tr>
			  <th>Items</th>
			  <th>Descripcion</th>
			  <th>Apagar</th>
			</tr>
		  </thead>

		  <tbody>
				<tr>
					<td>1</td>
					<td>Fondo de Reserva</td>
					<td>2.500</td>
				</tr>
				<tr>
					<td>2</td>
					<td>Fondo de indemnnizacion</td>
					<td>0</td>
				</tr>
				<tr>
					<td>Total</td>
					<td></td>
					<td>Pagar</td>
				</tr>

		  </tbody>
		</table>
	  </div>
	</div>
  </div>

  <div class="card shadow mb-4">

	<div class="card-body">
	  <div class="table-responsive">
		<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
			<div class="form-group row">
				<div class="col-md-8">
					<h3>Saldo Pendiente del Gasto Comun</h3>
				</div>
		  </div>
		  <thead>
			<tr>
				<th>Items</th>
				<th>Descripcion</th>
				<th>Apagar</th>
			</tr>
		  </thead>

		  <tbody>
				<tr>
					<td>1</td>
					<td>Saldo Pendiente</td>
					<td>122.200</td>
				</tr>
				<tr>
					<td>2</td>
					<td>Interes por Atraso</td>
					<td>3.900</td>
				</tr>
				<tr>
					<td>3</td>
					<td>Multa por Atraso</td>
					<td>0</td>
				</tr>
				<tr>
					<td>Total</td>
					<td></td>
					<td>Pagar</td>
				</tr>


		  </tbody>
		</table>
	  </div>
	</div>
  </div>
@endsection

@section('scripts')

	<!-- Page level plugins -->
	<script src="vendor/datatables/jquery.dataTables.min.js"></script>
	<script src="vendor/datatables/dataTables.bootstrap4.min.js"></script>

	<!-- Page level custom scripts -->
	<script src="js/demo/datatables-demo.js"></script>
	<script src="js/serializeObject.js"></script>
	<script type="text/javascript">
		$(function () {

		})
	</script>
@endsection

resources/views/clients/rent.blade.php
@extends('layouts.app')

@section('css')
	<link href="/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection

@section('content')

<div class="col-md-8">
	<h1>Arrendar Lugar</h1>
</div>

<div class="card shadow mb-4">

	<div class="card-body">
	  <div class="table-responsive">
		<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
			<div class="form-group row">
		  </div>
		  <thead>
			<tr>
			  <th>Nombre</th>
			  <th>Precio</th>
              <th>Garantia</th>
              <th>Valor Multa</th>
			  <th>Lugar</th>
			  <th>Arrendarlo</th>
			</tr>
		  </thead>

		  <tbody>
			@foreach ($items as $key => $u)
				  <tr>
					<td>{{$u->name}}</td>
					<td>${{$u->price}}CLP</td>
                    <td>{{$u->waranty}}</td>
                    <td>${{$u->penalty}}CLP</td>
                    <td>
                        {{$types[$u->type]}}
                        @if ($u->type == 2)
                            <span>/ {{$u->structure->name}}</span>
                        @endif
					</td>
					<td>Pagar</td>
				</tr>
			@endforeach

		  </tbody>
		</table>
	  </div>
	</div>
  </div>
@endsection

@section('scripts')

	<!-- Page level plugins -->
	<script src="vendor/datatables/jquery.dataTables.min.js"></script>
	<script src="vendor/datatables/dataTables.bootstrap4.min.js"></script>

	<!-- Page level custom scripts -->
	<script src="js/demo/datatables-demo.js"></script>
	<script src="js/serializeObject.js"></script>
	<script type="text/javascript">
		$(function () {

		})
	</script>
@endsection