routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/edificios', 'BuildingController');

Route::resource('/estructura', 'BuildingItemsController');

Route::resource('/espacios', 'SpaceController');

Route::resource('/egresos', 'ExpenseController');

Route::resource('/asociaciones', 'ResidentUnityController');

Route::resource('/fondos', 'FundController');

Route::resource('/items_individuales', 'IndividualItemsController');

Route::resource('/gastos_individuales', 'IndividualExpensesController');

Route::resource('/servicios_individuales', 'IndividualItemsController');

Route::resource('/proveedores', 'ProvidersController');

Route::resource('/unidades', 'UnityController');

Route::resource('/usuario', 'UserController');

Route::get('/usuarioMyExpenses', 'UserController@myExpense');

Route::get('/usuarioBuildingExpenses', 'UserController@buildingExpense');

Route::get('/usuarioRent', 'UserController@rent');

Route::resource('/extension_unidad', 'UnityExtensionController');

Route::get('/dashboard/{id}', 'HomeController@dashboard');

Route::post('/unidades/import', 'UnityController@import');

Route::get('/personal', 'UserController@personal');

Route::get('/inquilino', 'UserController@inquilino');

Route::get('/getIndividualByUnity/{unity_id}', 'HelperController@getIndividualByUnity');

Route::get('/getInquilino/{unity_id}', 'HelperController@getInquilino');

Route::post('/createIndividual', 'HelperController@createIndividual');

Route::get('/gastos_unidad', 'UnityController@expenses');

Route::get('/userLogout', 'HomeController@userLogout');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
		'rut', 'phone', 'type',
		'building_id', 'unity_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

	const TYPES = [
		0=>'Super Admin',
		1=>'Admin',
		2=>'Usuario',
		3=>'Propietario',
		4=>'Residente',
		5=>'Personal',
		6=>'Comite'
	];
	//comite puede ver lo que pasa en el edificio solo para ver
	//

	public function personalDetail()
	{
		return $this->hasOne('App\PersonalDetails');
	}

	public function residentunity()
	{
		return $this->hasMany('App\ResidentUnity');
	}

	public function getTypeLabelAttribute()
	{
		return Self::TYPES[$this->type];
    }
    
    public function getAlicuotaAttribute() {
        $pro = 0;
        foreach ($this->residentunity as $key => $d) {
            $pro = (float)$d->unity->prorateo + (float)$pro;
        }
        return $pro;
    }

}

resources/views/individual/adminList.blade.php
@extends('layouts.app')

@section('css')
	<link href="/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection

@section('content')


	  <!-- Page Heading -->
	  <div class="d-sm-flex align-items-center justify-content-between mb-4">
		<h1 class="h3 mb-0 text-gray-800">Gastos Individuales</h1>


	  </div>

	  <div class="card shadow mb-4">
		  <div class="card-header">

 	 		<form action="/servicios_individuales" method="post" class="form-inline float-right egresoForm">
 	 			{{ csrf_field() }}
 	 			<input type="hidden" name="building_id" value="{{$build->id}}">
 	 		  	<input type="text" name="label" class="form-control mb-2 mr-sm-2" placeholder="Nombre" style="    min-width: 300px;">
				<div class="input-group mb-2 mr-sm-2" style="    min-width: 300px;">
					<select class="form-control" name="type">
						<option value="">Seleccione Tipo</option>
						<option value="1">Gasto</option>
						<option value="2">Lectura</option>
					</select>
				</div>
 	 		  <button type="submit" class="btn btn-primary mb-2">Crear</button>
 	 		</form>
 	   	</div>

		<div class="card-body">
		  <div class="table-responsive">
			<table class="table table-bordered" id="" width="100%" cellspacing="0">
			  <thead>
				<tr>
				  <th>Nombre</th>
				  <th>Tipo</th>
				  <th>#</th>
				</tr>
			  </thead>

			  <tbody>
				@foreach ($indItems as $key => $u)
				  	<tr>
						<td>{{$u->label}}</td>
						<td>{{$u->type_label}}</td>
						<td data-id="{{$u->id}}">
							<a href="#" class="btn btn-info btn-circle btn-sm editModal" data-toggle="tooltip" data-placement="top" title="Editar">
								<i class="fas fa-pencil-alt"></i>
							</a>
							<form style="display:inline" action="{{ url('/servicios_individuales/'.$u->id) }}" method="post">
								<button  type="submit" class="btn btn-danger btn-circle btn-sm">
    								<i class="fas fa-trash" data-toggle="tooltip" data-placement="top" title="Borrar"></i>
    							</button>
							    {!! method_field('delete') !!}
							    {!! csrf_field() !!}
							</form>

						</td>
					</tr>
				@endforeach

			  </tbody>
			</table>
		  </div>
		</div>
	  </div>


@endsection
@section('scripts')

	@include('individual.editModal')

	<!-- Page level plugins -->
	<script src="vendor/datatables/jquery.dataTables.min.js"></script>
	<script src="vendor/datatables/dataTables.bootstrap4.min.js"></script>

	<!-- Page level custom scripts -->
	<script src="js/demo/datatables-demo.js"></script>
	<script src="js/serializeObject.js"></script>
	<script type="text/javascript">
		$(function () {
			$('[data-toggle="tooltip"]').tooltip()

			$('body').on('click', '.editModal', function(){
				var id = $(this).parent().data('id')
				$.get('/servicios_individuales/'+id+'/edit', function(r){
					$('#editForm').attr('action', "/servicios_individuales/"+r.id);
					$('#editForm input[name=label]').val(r.label);
					$('#editForm select[name=type]').val(r.type);
					$('#editModal').modal()
				})
			})




		})
	</script>
@endsection

resources/views/individual/editModal.blade.php
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
	<div class="modal-content">
	  <div class="modal-header">
		<h5 class="modal-title" id="exampleModalLabel">Editar Gasto Individual</h5>
		<button class="close" type="button" data-dismiss="modal" aria-label="Close">
		  <span aria-hidden="true">×</span>
		</button>
	  </div>
	  <div class="modal-body">
		  <form id="editForm" action="/proveedores" method="post">
			  @csrf
			   <input name="_method" type="hidden" value="PUT">
			  <input type="hidden" name="building_id" value="{{$build->id}}">
			  	<div class="form-group row">
				  	<div class="col-md-12">
					  	<label for="">Nombre</label><br>
					 	<input type="text" class="form-control" name="label" value="">
				  	</div>
			  	</div>
			  	<div class="form-group row">
				  	<div class="col-md-12">
					  	<label for="">Tipo</label><br>
						<select class="form-control" name="type">
							<option value="">Seleccione Tipo</option>
							<option value="1">Gasto</option>
							<option value="2">Lectura</option>
							
						</select>
				  	</div>
			  	</div>

	  </div>
	  <div class="modal-footer">
		<button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
		<button class="btn btn-primary" type="submit">Guardar</button>
	  </div>
	  </form>
	</div>
  </div>
</div>